// Enrollment bootstrap for an already verified standalone release. Distribution is handled by
// the signed artifact installer; this script never downloads executable code or stores a bearer
// credential. The private key is generated by the agent bundle and only the CSR reaches the API.
export function buildInstallScript(apiUrl: string): string {
  return `#!/usr/bin/env bash
set -euo pipefail

: "\${MULTICA_ENROLL_CODE:?one-time enrollment code is required}"
API_URL="\${MULTICA_API_URL:-${apiUrl}}"
AGENT_HOME="\${MULTICA_AGENT_HOME:-/var/lib/3mf-device-agent}"
AGENT_ENTRYPOINT="\${DEVICE_AGENT_ENTRYPOINT:-/opt/3mf-device-agent/current/.release-dist/main.js}"

test -f "$AGENT_ENTRYPOINT" || { echo "verified device-agent release is not installed" >&2; exit 1; }
exec env MULTICA_API_URL="$API_URL" MULTICA_ENROLL_CODE="$MULTICA_ENROLL_CODE" MULTICA_AGENT_HOME="$AGENT_HOME" \
  /usr/bin/node "$AGENT_ENTRYPOINT" --enroll
`;
}
