**

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!version.json

!scripts/
!scripts/install-git-hooks.mjs

!apps/
!apps/web/
!apps/web/**

!packages/
!packages/config/
!packages/config/**
!packages/contracts/
!packages/contracts/**

**/node_modules
**/dist
**/.turbo
**/.vite
**/.vite-temp
**/test-results
**/.omc
