import { randomUUID } from "node:crypto";
import type { NestExpressApplication } from "@nestjs/platform-express";
import { SignJWT } from "jose";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { pool } from "../../../db/client.ts";
import { AppModule } from "../../../nest/app.module.ts";
import { createNestApp } from "../../../nest/bootstrap.ts";
import { registerTestBrowserSession } from "../../../test/session-verifier-test-providers.ts";

const secret = "sanctions-http-integration-test-secret"; const ids = { creator: randomUUID(), resolver: randomUUID(), target: randomUUID(), stranger: randomUUID() };
let app: NestExpressApplication; let baseUrl: string;
async function bearer(id: string) { const session = await registerTestBrowserSession(pool, id); return `Bearer ${await new SignJWT({ username: "appeals", sv: 1 }).setProtectedHeader({ alg: "HS256" }).setSubject(id).setJti(session.id).setExpirationTime(session.expiresAt).sign(new TextEncoder().encode(secret))}`; }
async function post(path: string, id: string, body: unknown) { return fetch(`${baseUrl}${path}`, { method: "POST", headers: { authorization: await bearer(id), "content-type": "application/json" }, body: JSON.stringify(body) }); }
async function get(path: string, id: string) { return fetch(`${baseUrl}${path}`, { headers: { authorization: await bearer(id) } }); }
async function sanction(state: "active" | "cancelled" | "expired" = "active") { const row = await pool.query<{ id: string }>(`insert into sanctions(user_id,type,state,reason_code,starts_at,created_by,idempotency_key,idempotency_payload_hash,cancelled_at,cancelled_by,cancel_reason) values($1::uuid,'ban',$2::text,'fraud',now(),$3::uuid,$4::text,$5::bytea,case when $2::text='cancelled' then now() else null end,case when $2::text='cancelled' then $3::uuid else null end,case when $2::text='cancelled' then 'fixture' else null end) returning id`, [ids.target, state, ids.creator, randomUUID(), Buffer.alloc(32)]); if (state === "active") await pool.query(`update users set status='restricted', session_version=session_version+1 where id=$1::uuid`, [ids.target]); return row.rows[0]!.id; }

describe.skipIf(!process.env.DATABASE_URL)("sanction appeals HTTP API", () => {
  beforeAll(async () => { process.env.JWT_SECRET = secret; await pool.query(`insert into users(id,username) values($1::uuid,$2::text),($3::uuid,$4::text),($5::uuid,$6::text),($7::uuid,$8::text)`, [ids.creator, `appeal-creator-${randomUUID()}`, ids.resolver, `appeal-resolver-${randomUUID()}`, ids.target, `appeal-target-${randomUUID()}`, ids.stranger, `appeal-stranger-${randomUUID()}`]); await pool.query(`insert into permission_grants(user_id, permission, granted_by, reason) values($1::uuid, 'moderation.manage_sanctions', $1::uuid, 'test fixture'),($2::uuid, 'moderation.resolve_appeal', $2::uuid, 'test fixture'),($2::uuid, 'moderation.view_reports', $2::uuid, 'test fixture')`, [ids.creator, ids.resolver]); app = await createNestApp(AppModule); await app.listen(0, "127.0.0.1"); const address = (app.getHttpServer() as { address(): { port: number } | null }).address(); if (!address) throw new Error("server did not bind"); baseUrl = `http://127.0.0.1:${address.port}`; });
  beforeEach(async () => { await pool.query(`delete from sanction_appeals where sanction_id in (select id from sanctions where user_id=$1::uuid)`, [ids.target]); await pool.query(`delete from sanctions where user_id=$1::uuid`, [ids.target]); await pool.query(`update users set status='active', session_version=1 where id=$1::uuid`, [ids.target]); });
  afterAll(async () => { await app?.close(); const userIds = [...Object.values(ids)]; await pool.query(`delete from sanction_appeals where sanction_id in (select id from sanctions where user_id=$1)`, [ids.target]); await pool.query(`delete from sanctions where user_id=$1`, [ids.target]); await pool.query(`delete from permission_grants where user_id = any($1::uuid[]) or granted_by = any($1::uuid[])`, [userIds]); await pool.query(`delete from users where id = any($1::uuid[])`, [userIds]); });
  it("keeps active-sanction target appeal HTTP flow restricted in the MVP", async () => { const id = await sanction(); expect((await post(`/sanctions/${id}/appeals`, ids.target, { message: "review" })).status).toBe(401); expect((await post(`/sanctions/${id}/appeals`, ids.creator, { message: "review" })).status).toBe(403); expect((await post(`/sanctions/${id}/appeals`, ids.stranger, { message: "review" })).status).toBe(403); });
  it("rejects cancelled and expired submissions", async () => { const cancelled = await sanction("cancelled"); await pool.query(`update users set status='active', session_version=1 where id=$1::uuid`, [ids.target]); expect((await post(`/sanctions/${cancelled}/appeals`, ids.target, { message: "review" })).status).toBe(409); const expired = await sanction("expired"); await pool.query(`update users set status='active', session_version=1 where id=$1::uuid`, [ids.target]); expect((await post(`/sanctions/${expired}/appeals`, ids.target, { message: "review" })).status).toBe(409); });
  it("lists and resolves pending appeals without cancelling the sanction", async () => { const id = await sanction(); const appeal = (await pool.query<{ id: string }>(`insert into sanction_appeals(sanction_id,submitted_by,message) values($1::uuid,$2::uuid,'review') returning id`, [id, ids.target])).rows[0]!.id; expect((await get(`/sanctions/${id}/appeals`, ids.resolver)).status).toBe(200); expect((await get(`/sanctions/${id}/appeals`, ids.target)).status).toBe(401); expect((await get(`/sanctions/${id}/appeals`, ids.stranger)).status).toBe(403); expect((await post(`/appeals/${appeal}/resolve`, ids.target, { state: "accepted", resolutionNote: "ok" })).status).toBe(401); expect((await post(`/appeals/${appeal}/resolve`, ids.creator, { state: "accepted", resolutionNote: "ok" })).status).toBe(403); expect((await post(`/appeals/${appeal}/resolve`, ids.resolver, { state: "accepted", resolutionNote: "ok" })).status).toBe(200); await expect(pool.query(`select state from sanctions where id=$1::uuid`, [id])).resolves.toMatchObject({ rows: [{ state: "active" }] }); });
  it("rejects a second pending appeal through the repository constraint", async () => { const id = await sanction(); await pool.query(`insert into sanction_appeals(sanction_id,submitted_by,message) values($1::uuid,$2::uuid,'review')`, [id, ids.target]); await expect(pool.query(`insert into sanction_appeals(sanction_id,submitted_by,message) values($1::uuid,$2::uuid,'again')`, [id, ids.target])).rejects.toMatchObject({ code: "23505" }); });
});
