import { randomUUID } from "node:crypto";
import type { NestExpressApplication } from "@nestjs/platform-express";
import { SignJWT } from "jose";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { pool } from "../../../db/client.ts";
import { AppModule } from "../../../nest/app.module.ts";
import { createNestApp } from "../../../nest/bootstrap.ts";
import { registerTestBrowserSession } from "../../../test/session-verifier-test-providers.ts";

const secret = "sanctions-http-integration-test-secret"; const ids = { staff: randomUUID(), user: randomUUID(), target: randomUUID(), targetTwo: randomUUID() };
let app: NestExpressApplication; let baseUrl: string;
async function bearer(id: string) { const session = await registerTestBrowserSession(pool, id); return `Bearer ${await new SignJWT({ username: "sanctions", sv: 1 }).setProtectedHeader({ alg: "HS256" }).setSubject(id).setJti(session.id).setExpirationTime(session.expiresAt).sign(new TextEncoder().encode(secret))}`; }
async function request(path: string, id: string | undefined, body?: unknown) { return fetch(`${baseUrl}${path}`, { method: body === undefined ? "GET" : "POST", headers: { ...(id ? { authorization: await bearer(id) } : {}), "content-type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) }); }
const payload = (targetId: string, key = randomUUID()) => ({ targetId, type: "ban", reasonCode: "fraud", idempotencyKey: key });

describe.skipIf(!process.env.DATABASE_URL)("sanctions HTTP API", () => {
  beforeAll(async () => { process.env.JWT_SECRET = secret; await pool.query(`insert into users(id,username) values($1,$2),($3,$4),($5,$6),($7,$8)`, [ids.staff, `sanctions-staff-${randomUUID()}`, ids.user, `sanctions-user-${randomUUID()}`, ids.target, `sanctions-target-${randomUUID()}`, ids.targetTwo, `sanctions-target-two-${randomUUID()}`]); await pool.query(`insert into permission_grants(user_id, permission, granted_by, reason) values($1, 'moderation.manage_sanctions', $1, 'test fixture'),($1, 'moderation.view_reports', $1, 'test fixture')`, [ids.staff]); app = await createNestApp(AppModule); await app.listen(0, "127.0.0.1"); const address = (app.getHttpServer() as { address(): { port: number } | null }).address(); if (!address) throw new Error("server did not bind"); baseUrl = `http://127.0.0.1:${address.port}`; });
  afterAll(async () => { await app?.close(); const userIds = [...Object.values(ids)]; await pool.query(`delete from outbox_events where aggregate_type='Sanction' and aggregate_id in (select id from sanctions where user_id = any($1::uuid[]))`, [[ids.target, ids.targetTwo]]); await pool.query(`delete from sanctions where user_id = any($1::uuid[])`, [[ids.target, ids.targetTwo]]); await pool.query(`delete from permission_grants where user_id = any($1::uuid[]) or granted_by = any($1::uuid[])`, [userIds]); await pool.query(`delete from users where id = any($1::uuid[])`, [userIds]); });
  it("enforces authentication and staff creation", async () => { expect((await request("/sanctions", undefined, payload(ids.target))).status).toBe(401); expect((await request("/sanctions", ids.user, payload(ids.target))).status).toBe(403); expect((await request("/sanctions", ids.staff, payload(ids.target))).status).toBe(201); });
  it("validates create payloads before the service", async () => { for (const body of [{ ...payload(ids.targetTwo), reasonCode: "legacy" }, { ...payload(ids.targetTwo), endsAt: "2000-01-01T00:00:00.000Z" }, { targetId: ids.targetTwo, type: "ban", reasonCode: "fraud" }, { ...payload(ids.targetTwo), evidenceUrl: "ftp://example.test" }, { ...payload(ids.staff) }]) expect((await request("/sanctions", ids.staff, body)).status).toBe(400); });
  it("handles retry, cancel, and self-or-staff reads", async () => { const key = randomUUID(); const first = await request("/sanctions", ids.staff, payload(ids.targetTwo, key)); const result = await first.json() as { sanction: { id: string } }; const retry = await request("/sanctions", ids.staff, payload(ids.targetTwo, key)); expect(retry.status).toBe(201); await expect(retry.json()).resolves.toMatchObject({ reused: true }); expect((await request("/sanctions", ids.staff, { ...payload(ids.targetTwo, key), reasonCode: "abuse" })).status).toBe(409); expect((await request(`/users/${ids.targetTwo}/sanctions/active`, ids.user)).status).toBe(403); expect((await request(`/users/${ids.targetTwo}/sanctions/active`, ids.staff)).status).toBe(200); expect((await request(`/users/${ids.user}/sanctions/active`, ids.user)).status).toBe(200); expect((await request(`/users/${ids.targetTwo}/sanctions/history`, ids.user)).status).toBe(403); expect((await request(`/users/${ids.user}/sanctions/history`, ids.user)).status).toBe(200); expect((await request(`/sanctions/${result.sanction.id}/cancel`, ids.user, { cancelReason: "no" })).status).toBe(403); expect((await request(`/sanctions/${result.sanction.id}/cancel`, ids.staff, { cancelReason: "reviewed" })).status).toBe(200); expect((await request(`/sanctions/${result.sanction.id}/cancel`, ids.staff, { cancelReason: "again" })).status).toBe(409); expect((await request(`/users/${ids.targetTwo}/sanctions/history`, ids.staff)).status).toBe(200); });
});
