import { randomUUID } from "node:crypto";
import { afterAll, describe, expect, it } from "vitest";
import { pool } from "../../../db/client.ts";
import { UserId } from "../../_kernel/brandedIds.ts";
import { ProfileRepository } from "../../profile/infrastructure/profile.repository.ts";
import { SanctionsRepository } from "../infrastructure/sanctions.repository.ts";
import { SanctionsExpirationService } from "./sanctions-expiration.service.ts";

const users: string[] = []; const sanctions: string[] = [];
async function fixture(input: { state?: "active" | "cancelled" | "expired"; endsAt?: Date | null; restricted?: boolean } = {}) {
  const user = (await pool.query<{ id: string }>(`insert into users(username,status) values($1,$2) returning id`, [`sanctions-expire-${randomUUID()}`, input.restricted ? "restricted" : "active"])).rows[0]!.id; users.push(user);
  const sanction = (await pool.query<{ id: string }>(`insert into sanctions(user_id,type,state,reason_code,starts_at,ends_at,created_by,idempotency_key,idempotency_payload_hash,cancelled_at,cancelled_by,cancel_reason) values($1::uuid,'ban',$2::text,'fraud',now()-interval '1 hour',$3::timestamptz,$1::uuid,$4::text,$5::bytea,case when $2::text='cancelled' then now() else null end,case when $2::text='cancelled' then $1::uuid else null end,case when $2::text='cancelled' then 'fixture' else null end) returning id`, [user, input.state ?? "active", input.endsAt === undefined ? new Date(Date.now() - 60_000) : input.endsAt, randomUUID(), Buffer.alloc(32)])).rows[0]!.id; sanctions.push(sanction); return { user: UserId(user), sanction };
}
function service() { return new SanctionsExpirationService(pool, new SanctionsRepository(pool), new ProfileRepository(pool)); }
afterAll(async () => { if (sanctions.length) await pool.query(`delete from sanctions where id=any($1::uuid[])`, [sanctions]); if (users.length) await pool.query(`delete from users where id=any($1::uuid[])`, [users]); });
describe.skipIf(!process.env.DATABASE_URL)("SanctionsExpirationService integration", () => {
  it("materializes a due active sanction and reactivates its restricted owner without changing session version", async () => { const item = await fixture({ restricted: true }); const before = await pool.query<{ session_version: number }>(`select session_version from users where id=$1`, [item.user]); await expect(service().expireDue({ limit: 500, workerId: "one" })).resolves.toMatchObject({ expired: 1, activatedUsers: 1 }); await expect(pool.query(`select state from sanctions where id=$1`, [item.sanction])).resolves.toMatchObject({ rows: [{ state: "expired" }] }); await expect(pool.query(`select status,session_version from users where id=$1`, [item.user])).resolves.toMatchObject({ rows: [{ status: "active", session_version: before.rows[0]!.session_version }] }); });
  it("leaves permanent, cancelled, and already-expired rows untouched", async () => { const permanent = await fixture({ endsAt: null, restricted: true }); const cancelled = await fixture({ state: "cancelled", restricted: true }); const expired = await fixture({ state: "expired", restricted: true }); const before = await pool.query<{ id: string; updated_at: Date }>(`select id,updated_at from sanctions where id=any($1::uuid[])`, [[permanent.sanction, cancelled.sanction, expired.sanction]]); await service().expireDue({ limit: 500, workerId: "one" }); const after = await pool.query<{ id: string; state: string; updated_at: Date }>(`select id,state,updated_at from sanctions where id=any($1::uuid[])`, [[permanent.sanction, cancelled.sanction, expired.sanction]]); expect(after.rows).toEqual(expect.arrayContaining(before.rows.map((row) => expect.objectContaining({ id: row.id, updated_at: row.updated_at })))); });
  it("processes each due sanction once across concurrent workers", async () => { const first = await fixture({ restricted: true }); const second = await fixture({ restricted: true }); await Promise.all([service().expireDue({ limit: 500, workerId: "one" }), service().expireDue({ limit: 500, workerId: "two" })]); await expect(pool.query(`select count(*)::int as count from sanctions where id=any($1::uuid[]) and state='expired'`, [[first.sanction, second.sanction]])).resolves.toMatchObject({ rows: [{ count: 2 }] }); });
});
