import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { ReactNode } from "react";
import { AdminScreen } from "./adminscreen.tsx";

vi.mock("@platform/nav", () => ({ AdministrationShell: ({ children }: { children: ReactNode }) => <>{children}</> }));
const api = vi.hoisted(() => ({
  openModal:vi.fn((_options:{readonly size:string;readonly title:string;readonly content:ReactNode})=>({close:vi.fn()})),getAdminMe:vi.fn(),browseAdminUsers:vi.fn(),searchAdminUsers:vi.fn(),getAdminUser:vi.fn(),getAdminUserAccess:vi.fn(),getAdminPermissionCatalog:vi.fn(),previewPermissionChange:vi.fn(),executePermissionChange:vi.fn(),previewAccessConfiguration:vi.fn(),executeAccessConfiguration:vi.fn(),getAdminUserSessions:vi.fn(),previewAdminOperation:vi.fn(),executeAdminOperation:vi.fn(),getAdminAuditEvents:vi.fn(),createAdminAuditExport:vi.fn(),downloadAdminAuditExport:vi.fn(),
}));
vi.mock("./api.ts", () => api);
vi.mock("@platform/overlay",()=>({useOverlay:()=>({modal:api.openModal})}));
afterEach(() => { cleanup(); vi.clearAllMocks(); });

const props = { user:{id:"actor",username:"admin",display_name:"Admin",avatar_url:null,handle_confirmed:true,role:"user" as const,capabilities:["admin.portal.access" as const]},section:"home" as const,onSectionChange:()=>undefined };
const grant = (key:string) => ({key,scope:{kind:"global"},expires_at:null});
const target = {id:"00000000-0000-4000-8000-000000000002",username:"target",display_name:"Target User",status:"active" as const,role:"admin" as const,account_state:"active" as const,created_at:"2026-01-01T00:00:00.000Z",updated_at:"2026-01-01T00:00:00.000Z",pii_masked:true as const};
const access = {admin_preset:{key:"admin.default",version:1,permissions:["admin.portal.access","admin.view_permission_catalog","user.view_any","analytics.view_health"]},assignment:{id:"00000000-0000-4000-8000-000000000003",preset_key:"admin.default",preset_version:1,preset_snapshot:["admin.portal.access"],assigned_at:"2026-01-01T00:00:00.000Z",missing_snapshot_permissions:[],additional_direct_permissions:["catalog.edit_any"],current_preset_added:[],current_preset_removed:[]},grants:[{id:"00000000-0000-4000-8000-000000000004",permission:"admin.portal.access",scope:{kind:"global"},expires_at:null,provenance:"admin_assignment",assignment_id:"00000000-0000-4000-8000-000000000003"},{id:"00000000-0000-4000-8000-000000000005",permission:"catalog.edit_any",scope:{kind:"global"},expires_at:null,provenance:"direct",assignment_id:null}]};

describe("AdminScreen", () => {
  it("applies the administrator template as editable checkboxes", async () => {
    const preset=["admin.portal.access","admin.view_permission_catalog","user.view_any"];
    api.getAdminMe.mockResolvedValue({user_id:"actor",permissions:["admin.portal.access","user.view_any","user.view_permissions","admin.view_permission_catalog","user.grant_permission","user.revoke_permission"].map(grant)});
    api.getAdminUser.mockResolvedValue(target);
    api.getAdminUserAccess.mockResolvedValue({admin_preset:{key:"admin.default",version:2,permissions:preset},assignment:null,grants:[]});
    api.getAdminPermissionCatalog.mockResolvedValue({items:preset.map(key=>({key,admin_assignable:true}))});
    render(<AdminScreen {...props} targetId={target.id}/>);
    fireEvent.click(await screen.findByRole("button",{name:"Настроить доступ"}));
    render(<>{api.openModal.mock.calls[0]?.[0].content}</>);
    fireEvent.click(screen.getByRole("radio",{name:"Администратор"}));
    for(const checkbox of screen.getAllByRole("checkbox")){
      expect(checkbox).toHaveProperty("checked",true);
      expect(checkbox.hasAttribute("disabled")).toBe(false);
    }
    fireEvent.click(screen.getByRole("checkbox",{name:/Просмотр каталога разрешений/}));
    expect(screen.getByRole("radio",{name:"Пользователь"})).toHaveProperty("checked",true);
  });
  it("saves access configuration without a password", async () => {
    api.getAdminMe.mockResolvedValue({user_id:"actor",permissions:["admin.portal.access","user.view_any","user.view_permissions","admin.view_permission_catalog","user.grant_permission","user.revoke_permission","user.assign_admin","user.remove_admin_assignment"].map(grant)});
    api.getAdminUser.mockResolvedValue(target);
    api.getAdminUserAccess.mockResolvedValue(access);
    api.getAdminPermissionCatalog.mockResolvedValue({items:[]});
    api.previewAccessConfiguration.mockResolvedValue({confirmation_id:"intent",effects:{added:[],revoked:[]}});
    api.executeAccessConfiguration.mockResolvedValue({});
    render(<AdminScreen {...props} targetId={target.id}/>);
    fireEvent.click(await screen.findByRole("button",{name:"Настроить доступ"}));
    render(<>{api.openModal.mock.calls[0]?.[0].content}</>);
    fireEvent.click(screen.getByRole("button",{name:"Сохранить"}));
    const confirm = await screen.findByRole("button",{name:"Подтвердить и сохранить"});
    expect(screen.queryByLabelText("Пароль Superadmin")).toBeNull();
    expect(confirm.hasAttribute("disabled")).toBe(false);
    fireEvent.click(confirm);
    await waitFor(()=>expect(api.executeAccessConfiguration).toHaveBeenCalledWith(target.id,expect.objectContaining({confirmation_id:"intent"})));
    expect(api.executeAccessConfiguration.mock.calls[0]?.[1]).not.toHaveProperty("password");
  });
  it("keeps content above Aurora", () => { expect(readFileSync(resolve(process.cwd(),"src/domains/admin/adminscreen.css"),"utf8")).toMatch(/\.adminWorkspace\s*\{[^}]*z-index:\s*1/); });
  it("denies the workspace without its shell permission", async () => { api.getAdminMe.mockRejectedValue({status:403});render(<AdminScreen {...props}/>);expect(await screen.findByText("Нет доступа к административному пространству")).toBeTruthy();expect(api.browseAdminUsers).not.toHaveBeenCalled(); });
  it("shows role and account state in the directory", async () => { api.getAdminMe.mockResolvedValue({user_id:"actor",permissions:[grant("admin.portal.access"),grant("user.view_any")]});api.browseAdminUsers.mockResolvedValue({items:[target],next_cursor:null});render(<AdminScreen {...props}/>);expect(await screen.findByText("Администратор")).toBeTruthy();expect(screen.getByText("Активен")).toBeTruthy(); });
  it("renders general audit only on its dedicated screen and keeps server pagination", async () => { api.getAdminMe.mockResolvedValue({user_id:"actor",permissions:[grant("admin.portal.access"),grant("audit.view_log")]});api.getAdminAuditEvents.mockResolvedValueOnce({items:[{id:"e1",actor_user_id:"a",action:"admin.user.viewed",target_type:"user",target_id:"u",created_at:"2026-09-25T00:00:00Z",metadata:{},details_masked:true}],next_cursor:"next",range:{from:"2026-08-25T00:00:00Z",to:"2026-09-25T00:00:00Z"}}).mockResolvedValueOnce({items:[],next_cursor:null,range:{from:"2026-08-25T00:00:00Z",to:"2026-09-25T00:00:00Z"}});render(<AdminScreen {...props} view="audit"/>);expect(await screen.findByText("Открыта карточка пользователя")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Показать ещё события"}));await waitFor(()=>expect(api.getAdminAuditEvents).toHaveBeenLastCalledWith({cursor:"next",targetId:undefined})); });
  it("edits role and permissions through the platform overlay", async () => { api.getAdminMe.mockResolvedValue({user_id:"actor",permissions:[grant("admin.portal.access"),grant("user.view_any"),grant("user.view_permissions"),grant("admin.view_permission_catalog"),grant("user.grant_permission"),grant("user.revoke_permission"),grant("user.assign_admin"),grant("user.remove_admin_assignment")]});api.getAdminUser.mockResolvedValue(target);api.getAdminUserAccess.mockResolvedValue(access);api.getAdminPermissionCatalog.mockResolvedValue({items:[{key:"admin.portal.access",admin_assignable:true},{key:"user.suspend",admin_assignable:true},{key:"catalog.edit_any",admin_assignable:true},{key:"analytics.view_platform",admin_assignable:false}]});render(<AdminScreen {...props} targetId={target.id}/>);fireEvent.click(await screen.findByRole("button",{name:"Настроить доступ"}));expect(api.openModal).toHaveBeenCalledWith(expect.objectContaining({size:"wide",title:"Роль и разрешения"}));render(<>{api.openModal.mock.calls[0]?.[0].content}</>);expect(screen.getByText("Доступ к разделу «Администрирование»")).toBeTruthy();expect(screen.getByText("Приостановка аккаунта")).toBeTruthy();expect(screen.getByText("Управление материалами")).toBeTruthy();expect(screen.queryByText("Просмотр продуктовой аналитики")).toBeNull();expect(screen.getByText(/admin\.portal\.access/)).toBeTruthy();expect(screen.queryByLabelText("Причина изменения")).toBeNull();expect(screen.getByRole("button",{name:"Сохранить"}).hasAttribute("disabled")).toBe(false);expect(screen.queryByText("Credentials")).toBeNull();expect(screen.queryByText("API keys")).toBeNull(); });
  it("keeps a direct permission checked when it also belongs to the Admin preset", async () => { const directAccess={...access,assignment:null,grants:[{id:"00000000-0000-4000-8000-000000000006",permission:"admin.portal.access",scope:{kind:"global"},expires_at:null,provenance:"direct",assignment_id:null}]};api.getAdminMe.mockResolvedValue({user_id:"actor",permissions:[grant("admin.portal.access"),grant("user.view_any"),grant("user.view_permissions"),grant("admin.view_permission_catalog"),grant("user.grant_permission"),grant("user.revoke_permission"),grant("user.assign_admin"),grant("user.remove_admin_assignment")]});api.getAdminUser.mockResolvedValue({...target,role:"user"});api.getAdminUserAccess.mockResolvedValue(directAccess);api.getAdminPermissionCatalog.mockResolvedValue({items:[{key:"admin.portal.access",admin_assignable:true}]});api.previewAccessConfiguration.mockResolvedValue({confirmation_id:"00000000-0000-4000-8000-000000000007",effects:{added:[],revoked:[]},expires_at:"2030-01-01T00:00:00.000Z"});render(<AdminScreen {...props} targetId={target.id}/>);fireEvent.click(await screen.findByRole("button",{name:"Настроить доступ"}));render(<>{api.openModal.mock.calls[0]?.[0].content}</>);const checkbox=screen.getByRole("checkbox",{name:/Доступ к разделу/}) as HTMLInputElement;expect(checkbox.checked).toBe(true);expect(checkbox.disabled).toBe(false);fireEvent.click(screen.getByRole("button",{name:"Сохранить"}));await waitFor(()=>expect(api.previewAccessConfiguration).toHaveBeenCalledWith(target.id,expect.objectContaining({permissions:["admin.portal.access"]}))); });
  it("preserves hidden backend grants without sending them through the access editor", async () => { const legacyAccess={...access,assignment:null,grants:[{id:"00000000-0000-4000-8000-000000000008",permission:"analytics.view_platform",scope:{kind:"global"},expires_at:null,provenance:"direct",assignment_id:null}]};api.getAdminMe.mockResolvedValue({user_id:"actor",permissions:[grant("admin.portal.access"),grant("user.view_any"),grant("user.view_permissions"),grant("admin.view_permission_catalog"),grant("user.grant_permission"),grant("user.revoke_permission"),grant("user.assign_admin"),grant("user.remove_admin_assignment")]});api.getAdminUser.mockResolvedValue({...target,role:"user"});api.getAdminUserAccess.mockResolvedValue(legacyAccess);api.getAdminPermissionCatalog.mockResolvedValue({items:[{key:"admin.portal.access",admin_assignable:true},{key:"analytics.view_platform",admin_assignable:false}]});api.previewAccessConfiguration.mockResolvedValue({confirmation_id:"00000000-0000-4000-8000-000000000009",effects:{added:[],revoked:[]},expires_at:"2030-01-01T00:00:00.000Z"});render(<AdminScreen {...props} targetId={target.id}/>);fireEvent.click(await screen.findByRole("button",{name:"Настроить доступ"}));render(<>{api.openModal.mock.calls[0]?.[0].content}</>);expect(screen.queryByText("Просмотр продуктовой аналитики")).toBeNull();fireEvent.click(screen.getByRole("button",{name:"Сохранить"}));await waitFor(()=>expect(api.previewAccessConfiguration).toHaveBeenCalledWith(target.id,expect.objectContaining({permissions:[]}))); });
  it("opens the protected Superadmin permissions as a read-only platform modal",async()=>{api.getAdminMe.mockResolvedValue({user_id:"actor",permissions:[grant("admin.portal.access"),grant("user.view_any"),grant("user.view_permissions")]});api.getAdminUser.mockResolvedValue({...target,role:"superadmin"});api.getAdminUserAccess.mockResolvedValue(access);render(<AdminScreen {...props} targetId={target.id}/>);fireEvent.click(await screen.findByRole("button",{name:"Просмотреть разрешения"}));render(<>{api.openModal.mock.calls[0]?.[0].content}</>);expect(screen.getByText(/управляются при запуске платформы/)).toBeTruthy();for(const checkbox of screen.getAllByRole("checkbox"))expect(checkbox.getAttribute("disabled")).not.toBeNull();expect(screen.queryByRole("button",{name:"Сохранить"})).toBeNull();expect(screen.queryByLabelText("Причина изменения")).toBeNull();expect(screen.getByRole("button",{name:"Закрыть"})).toBeTruthy();});
  it("confirms selective session revoke with one explicit danger action", async () => { api.getAdminMe.mockResolvedValue({user_id:"actor",permissions:[grant("admin.portal.access"),grant("user.view_any"),grant("user.view_sessions"),grant("user.manage_sessions")]});api.getAdminUser.mockResolvedValue(target);api.getAdminUserSessions.mockResolvedValue({items:[{id:"00000000-0000-4000-8000-000000000010",created_at:"2026-01-01T00:00:00Z",expires_at:"2030-01-01T00:00:00Z",last_seen_at:"2026-01-01T00:00:00Z",revoked_at:null}]});api.previewAdminOperation.mockResolvedValue({confirmation_id:"00000000-0000-4000-8000-000000000011",effects:{},expires_at:"2030-01-01T00:00:00.000Z"});api.executeAdminOperation.mockResolvedValue({action:"revoke_session"});render(<AdminScreen {...props} targetId={target.id}/>);fireEvent.click(await screen.findByRole("button",{name:"Завершить"}));expect(screen.getByRole("dialog",{name:"Завершить сессию"})).toBeTruthy();expect(screen.queryByRole("button",{name:"Рассчитать последствия"})).toBeNull();expect(screen.queryByText(/sessions_revoked/)).toBeNull();const confirm=screen.getByRole("button",{name:"Да, завершить сессию"});expect(confirm.classList.contains("danger")).toBe(true);expect(confirm.hasAttribute("disabled")).toBe(true);fireEvent.change(screen.getByLabelText("Пароль Superadmin"),{target:{value:"secret"}});fireEvent.click(screen.getByRole("button",{name:"Да, завершить сессию"}));await waitFor(()=>expect(api.executeAdminOperation).toHaveBeenCalledWith(target.id,"revoke_session",{password:"secret",confirmation_id:"00000000-0000-4000-8000-000000000011"},"00000000-0000-4000-8000-000000000010"));expect(api.previewAdminOperation).toHaveBeenCalledWith(target.id,"revoke_session","00000000-0000-4000-8000-000000000010");await waitFor(()=>expect(screen.queryByRole("dialog",{name:"Завершить сессию"})).toBeNull()); });
  it("downloads account metadata without preview UI or Superadmin password", async () => { const createObjectURL=vi.fn(()=>"blob:admin-export");const revokeObjectURL=vi.fn();Object.defineProperty(URL,"createObjectURL",{configurable:true,value:createObjectURL});Object.defineProperty(URL,"revokeObjectURL",{configurable:true,value:revokeObjectURL});vi.spyOn(HTMLAnchorElement.prototype,"click").mockImplementation(()=>undefined);api.getAdminMe.mockResolvedValue({user_id:"actor",permissions:[grant("admin.portal.access"),grant("user.view_any"),grant("user.export")]});api.getAdminUser.mockResolvedValue(target);api.previewAdminOperation.mockResolvedValue({confirmation_id:"00000000-0000-4000-8000-000000000012",effects:{},expires_at:"2030-01-01T00:00:00.000Z"});api.executeAdminOperation.mockResolvedValue({kind:"administrative_account_metadata_snapshot"});render(<AdminScreen {...props} targetId={target.id}/>);fireEvent.click(await screen.findByRole("button",{name:"Экспортировать метаданные"}));await waitFor(()=>expect(api.executeAdminOperation).toHaveBeenCalledWith(target.id,"export_account",{confirmation_id:"00000000-0000-4000-8000-000000000012"}));expect(api.previewAdminOperation).toHaveBeenCalledWith(target.id,"export_account");expect(screen.queryByRole("dialog",{name:"Экспортировать метаданные"})).toBeNull();expect(screen.queryByLabelText("Пароль Superadmin")).toBeNull();expect(createObjectURL).toHaveBeenCalledOnce();expect(revokeObjectURL).toHaveBeenCalledWith("blob:admin-export"); });
  it("shows contextual account actions with explicit closure and target audit wording", async () => { api.getAdminMe.mockResolvedValue({user_id:"actor",permissions:[grant("admin.portal.access"),grant("user.view_any"),grant("user.suspend"),grant("user.block"),grant("user.restore"),grant("user.delete"),grant("audit.view_log")]});api.getAdminUser.mockResolvedValue(target);api.getAdminAuditEvents.mockResolvedValue({items:[],next_cursor:null,range:{from:"2026-08-25T00:00:00Z",to:"2026-09-25T00:00:00Z"}});render(<AdminScreen {...props} targetId={target.id}/>);expect(await screen.findByRole("button",{name:"Приостановить"})).toBeTruthy();expect(screen.queryByRole("button",{name:"Восстановить"})).toBeNull();expect(screen.getByRole("heading",{name:"Закрытие аккаунта"})).toBeTruthy();expect(screen.queryByText("Опасная зона")).toBeNull();expect(screen.getByRole("heading",{name:"Административная история пользователя"})).toBeTruthy();expect(screen.getByText(/пользователь был объектом действия/)).toBeTruthy();expect(screen.getByRole("button",{name:"Закрыть аккаунт"})).toBeTruthy(); });
});
