// Historical Fastify baseline only. These routes stay in routes.manifest.json so the completed
// transport migration remains auditable; none is an active route or compatibility alias.
export const FORMALLY_REMOVED_ROUTES = new Map<string, string>([
  ["POST /internal/relay/session/open", "relay-nest-foundation"],
  ["POST /internal/relay/session/heartbeat", "relay-nest-foundation"],
  ["POST /internal/relay/session/close", "relay-nest-foundation"],
  ["POST /internal/relay/session/print-result", "relay-nest-foundation"],
  ["POST /internal/relay/commands/poll", "relay-nest-foundation"],
  ["POST /internal/relay/commands/:commandId/result", "relay-nest-foundation"],
  ["GET /internal/relay/transfers/:transferId/metadata", "relay-nest-foundation"],
  ["POST /internal/relay/transfers/:transferId/progress", "relay-nest-foundation"],
  ["GET /models/:id/makes/leaderboard", "project-api-v1"],
  ["POST /models", "project-api-v1"],
  ["GET /models", "project-api-v1"],
  ["GET /models/:id", "project-api-v1"],
  ["GET /models/:id/preview.glb", "project-api-v1"],
  ["GET /models/:id/thumb.webp", "project-api-v1"],
  ["GET /models/:id/preview.mobile.glb", "project-api-v1"],
  ["GET /models/:id/download.3mf", "project-api-v1"],
  ["GET /models/:id/download.stl", "project-api-v1"],
  ["GET /models/:id/files/:role/download", "project-api-v1"],
  ["POST /models/:id/description-images", "project-api-v1"],
  ["GET /models/:id/description-images/:fileId", "project-api-v1"],
  ["PATCH /models/:id", "project-api-v1"],
  ["DELETE /models/:id", "project-api-v1"],
  ["POST /models/:id/files", "project-api-v1"],
  ["DELETE /models/:id/files/:fileId", "project-api-v1"],
  ["GET /models/:id/tree", "project-api-v1"],
  ["GET /models/:id/readme", "project-api-v1"],
  ["GET /models/:id/history", "project-api-v1"],
  ["POST /models/:id/fork", "project-api-v1"],
  ["GET /models/:id/manifest", "project-api-v1"],
  ["POST /models/:id/featured", "project-api-v1"],
  ["POST /models/:id/vote", "project-api-v1"],
  ["GET /models/:id/comments", "project-api-v1"],
  ["POST /models/:id/comments", "project-api-v1"],
  ["DELETE /models/:id/comments/:commentId", "project-api-v1"],
  ["GET /models/:id/build-guide", "project-api-v1"],
  ["POST /models/:id/build-guide/steps", "project-api-v1"],
  ["PATCH /models/:id/build-guide/steps/:stepId", "project-api-v1"],
  ["DELETE /models/:id/build-guide/steps/:stepId", "project-api-v1"],
  ["PUT /models/:id/build-guide/steps/reorder", "project-api-v1"],
  ["POST /models/:id/build-guide/steps/:stepId/photos", "project-api-v1"],
  ["DELETE /models/:id/build-guide/steps/:stepId/photos/:photoId", "project-api-v1"],
  ["POST /models/:id/slice", "project-api-v1"],
  ["GET /slice-jobs/:jobId", "project-api-v1"],
  ["POST /models/:id/report", "project-api-v1"],
  ["POST /models/:id/reports/:reportId/resolve", "project-api-v1"],
  ["GET /tags", "project-api-v1"],
  ["GET /models/_index/scan", "project-api-v1"],
  ["GET /analytics/health", "obsolete-admin-permissions-cleanup"],
  ["GET /catalog/metrics", "obsolete-admin-permissions-cleanup"],
]);

export const RELAY_FORMALLY_REMOVED_COUNT = 8;
export const PROJECT_API_V1_FORMALLY_REMOVED_COUNT = 39;
