import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { INestApplication } from "@nestjs/common";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import routeManifest from "./routes.manifest.json" with { type: "json" };
import { createNestApp } from "../nest/bootstrap.ts";
import { createOpenApiDocument } from "../nest/openapi/setup-openapi.ts";
import { FORMALLY_REMOVED_ROUTES } from "./formallyRemovedRoutes.ts";

// Route-status ledger (backend-nest-migration task 5.2, spec api-runtime → «Критерии cutover и
// удаления Fastify» / scenario «остаётся список маршрутов с владельцем и статусом»).
//
// Assigns exactly one status to every one of the 315 baseline routes and proves there are ZERO
// active deferred Fastify routes (a route silently left on Fastify with no owning change). The
// generated ledger is written to inventory/route-status-ledger.md; this test both asserts the
// invariants AND checks the committed artifact is in sync (drift gate), analogous to openapi:check.
//
//   · migrated            — mounted in the Nest AppModule (owner: this change)
//   · formally-removed     — deliberately NOT in Nest, owned by a linked change (relay-nest-foundation)
//   · compatibility-removed— replaced by a compatibility adapter (none; Project API v1 is greenfield)
//
// "0 active deferred Fastify" = every baseline route is migrated OR formally-removed OR
// compatibility-removed; none is unaccounted.

const HTTP_METHODS = new Set(["delete", "get", "head", "options", "patch", "post", "put"]);

interface RouteEntry {
  readonly method: string;
  readonly path: string;
  readonly domain: string;
}

type RouteStatus = "migrated" | "formally-removed" | "compatibility-removed" | "deferred-fastify";

interface LedgerRow {
  readonly method: string;
  readonly path: string;
  readonly domain: string;
  readonly status: RouteStatus;
  readonly owner: string;
}

const routes = routeManifest as unknown as RouteEntry[];

function normalizePath(path: string): string {
  if (path === "/research/media/*") return "/research/media/{key}";
  return path.replace(/:([A-Za-z0-9_]+)/g, "{$1}");
}

function buildLedger(nestRoutes: ReadonlySet<string>): LedgerRow[] {
  return routes.map((route) => {
    const rawKey = `${route.method} ${route.path}`;
    const nestKey = `${route.method} ${normalizePath(route.path)}`;
    const linkedChange = FORMALLY_REMOVED_ROUTES.get(rawKey);

    let status: RouteStatus;
    let owner: string;
    if (nestRoutes.has(nestKey)) {
      status = "migrated";
      owner = "backend-nest-migration";
    } else if (linkedChange !== undefined) {
      status = "formally-removed";
      owner = linkedChange;
    } else {
      status = "deferred-fastify";
      owner = "UNOWNED";
    }
    return { method: route.method, path: route.path, domain: route.domain, status, owner };
  });
}

function renderLedgerMarkdown(ledger: readonly LedgerRow[]): string {
  const migrated = ledger.filter((r) => r.status === "migrated").length;
  const formallyRemoved = ledger.filter((r) => r.status === "formally-removed").length;
  const compatRemoved = ledger.filter((r) => r.status === "compatibility-removed").length;
  const deferred = ledger.filter((r) => r.status === "deferred-fastify").length;

  const byDomain = new Map<string, { migrated: number; formallyRemoved: number }>();
  for (const row of ledger) {
    const bucket = byDomain.get(row.domain) ?? { migrated: 0, formallyRemoved: 0 };
    if (row.status === "migrated") bucket.migrated += 1;
    if (row.status === "formally-removed") bucket.formallyRemoved += 1;
    byDomain.set(row.domain, bucket);
  }

  const lines: string[] = [];
  lines.push("# Route-status ledger (M1, task 5.2)");
  lines.push("");
  lines.push("Generated by `src/characterization/routeStatusLedger.test.ts`. Do not edit by hand — the test");
  lines.push("regenerates and drift-checks this file. Every one of the 315 baseline routes carries exactly");
  lines.push("one status; **0 active deferred Fastify** is the cutover gate (spec api-runtime).");
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push("| Status | Count | Owner |");
  lines.push("|---|---|---|");
  lines.push(`| migrated | ${migrated} | backend-nest-migration (Nest AppModule) |`);
  lines.push(`| formally-removed | ${formallyRemoved} | linked changes |`);
  lines.push(`| compatibility-removed | ${compatRemoved} | none (greenfield Project API v1) |`);
  lines.push(`| **deferred-fastify (unowned)** | **${deferred}** | **must be 0 for cutover** |`);
  lines.push(`| **Total** | **${ledger.length}** | |`);
  lines.push("");
  lines.push("## Migrated routes by domain");
  lines.push("");
  lines.push("| Domain | migrated | formally-removed |");
  lines.push("|---|---|---|");
  for (const domain of [...byDomain.keys()].sort()) {
    const bucket = byDomain.get(domain)!;
    lines.push(`| ${domain} | ${bucket.migrated} | ${bucket.formallyRemoved} |`);
  }
  lines.push("");
  lines.push("## Formally-removed routes (owned by a linked change, not deferred Fastify)");
  lines.push("");
  lines.push("| Route | Owner |");
  lines.push("|---|---|");
  for (const row of ledger.filter((r) => r.status === "formally-removed")) {
    lines.push(`| ${row.method} ${row.path} | ${row.owner} |`);
  }
  lines.push("");
  return `${lines.join("\n")}`;
}

const scriptDir = dirname(fileURLToPath(import.meta.url));
// Снимок хранится рядом с characterization suite, чтобы checkout был самодостаточным.
const LEDGER_PATH = join(scriptDir, "route-status-ledger.md");
const INVENTORY_LEDGER_PATH = join(scriptDir, "inventory", "route-status-ledger.md");

describe("route-status ledger (task 5.2)", () => {
  let app: INestApplication;
  let ledger: LedgerRow[];

  beforeAll(async () => {
    process.env.NODE_ENV = "test";
    process.env.JWT_SECRET = "route-status-ledger-test-secret";
    app = await createNestApp();
    await app.init();

    const nestRoutes = new Set<string>();
    const document = createOpenApiDocument(app);
    for (const [path, item] of Object.entries(document.paths)) {
      for (const method of Object.keys(item ?? {})) {
        if (HTTP_METHODS.has(method)) nestRoutes.add(`${method.toUpperCase()} ${normalizePath(path)}`);
      }
    }
    ledger = buildLedger(nestRoutes);
  });

  afterAll(async () => {
    await app?.close();
  });

  it("assigns exactly one status to all 315 baseline routes", () => {
    expect(ledger).toHaveLength(315);
    const counts = {
      migrated: ledger.filter((r) => r.status === "migrated").length,
      formallyRemoved: ledger.filter((r) => r.status === "formally-removed").length,
      compatibilityRemoved: ledger.filter((r) => r.status === "compatibility-removed").length,
      deferred: ledger.filter((r) => r.status === "deferred-fastify").length,
    };
    expect(counts).toEqual({ migrated: 266, formallyRemoved: 49, compatibilityRemoved: 0, deferred: 0 });
  });

  it("has ZERO active deferred Fastify routes (cutover gate)", () => {
    const deferred = ledger.filter((r) => r.status === "deferred-fastify").map((r) => `${r.method} ${r.path}`);
    expect(deferred, `unowned deferred Fastify routes:\n${deferred.join("\n")}`).toEqual([]);
  });

  it("every route has a concrete owner (no UNOWNED)", () => {
    const unowned = ledger.filter((r) => r.owner === "UNOWNED").map((r) => `${r.method} ${r.path}`);
    expect(unowned).toEqual([]);
  });

  it("keeps the committed ledger artifact in sync (drift gate)", async () => {
    const rendered = renderLedgerMarkdown(ledger);
    // One-shot regeneration: `LEDGER_WRITE=1` refreshes the committed artifact, mirroring the
    // openapi:generate/openapi:check split. CI runs without the flag → pure drift check.
    if (process.env.LEDGER_WRITE === "1") {
      await Promise.all([writeFile(LEDGER_PATH, rendered, "utf8"), writeFile(INVENTORY_LEDGER_PATH, rendered, "utf8")]);
    }
    const [committed, inventory] = await Promise.all([
      readFile(LEDGER_PATH, "utf8").catch(() => ""),
      readFile(INVENTORY_LEDGER_PATH, "utf8").catch(() => ""),
    ]);
    const message = "route-status ledger is stale. Regenerate with LEDGER_WRITE=1 vitest run src/characterization/routeStatusLedger.test.ts.";
    expect(committed, message).toBe(rendered);
    expect(inventory, message).toBe(rendered);
  });
});

export { buildLedger, renderLedgerMarkdown };
