apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: relay
  annotations:
    openshift.io/host.generated: "true"
spec:
  to:
    kind: Service
    name: relay
    weight: 100
  port:
    targetPort: gateway
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
