// eslint-disable-next-line boundaries/element-types -- легатное междоменное ребро (Этап 9): printing→ai PrinterRecord, развязка отложена до pages/DI. См. MIGRATION.md.
import type { PrinterRecord } from "@domains/ai";

// Фикстура каталога `/printers` (MF-927, docs/design/printers.catalog.md). Блокер зафиксирован
// UX §9.4 и в описании карточки: `GET /printers` ещё не публичный (канон MF-405 не сведён), поэтому
// экран сегодня рисуется поверх этого мока, повторяющего форму `PrinterRecord` (зеркало
// printer.schema.json, research/api.ts — та же форма, что отдаёт/примет реальный API). Когда
// `GET /printers` появится — меняется только api.ts (см. listPrinters ниже), вёрстка не трогается.

function emptyMeta(overrides: Partial<PrinterRecord["_meta"]> = {}): PrinterRecord["_meta"] {
  return {
    schema_version: "1.0",
    filled_by: "fixture",
    reviewed_by: null,
    confidence: "medium",
    gaps: [],
    verified: true,
    updated_at: "2026-06-01T00:00:00Z",
    ...overrides,
  };
}

function emptyMedia(overrides: Partial<PrinterRecord["media"]> = {}): PrinterRecord["media"] {
  return { hero: null, gallery: [], official_url: null, ...overrides };
}

// Фото — data URI SVG (детерминированный градиент-заглушка под "продуктовый кадр"), не внешний
// хост: скриншоты/офлайн-разработка не зависят от сети, при этом путь рендера фото (не заглушки
// §3) реально прогоняется хотя бы на части фикстур.
function demoPhoto(hueFrom: number, hueTo: number): string {
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='640' height='360'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0' stop-color='hsl(${hueFrom},55%,30%)'/><stop offset='1' stop-color='hsl(${hueTo},55%,45%)'/></linearGradient></defs><rect width='640' height='360' fill='url(#g)'/></svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

const FIXTURES: PrinterRecord[] = [
  {
    id: "creality.k1-max",
    slug: "creality.k1-max",
    brand: "Creality",
    model: "K1 Max",
    aliases: ["K1 Max"],
    released_at: "2024-01-15",
    status: "shipping",
    kinematics: "corexy",
    type: "fdm",
    enclosed: true,
    build_volume: { x: 300, y: 300, z: 300, shape: "rect", diameter: null },
    hotend: { max_temp_c: 300, max_flow_mm3s: 24, nozzle_default_mm: 0.4, nozzle_swappable: false, material: "hardened steel", hardened: true },
    bed: { max_temp_c: 100, surface: "PEI", auto_leveling: "strain-gauge" },
    speed: { max_speed_mms: 600, max_accel_mms2: 20000, input_shaping: true },
    multimaterial: { supported: false, system_name: null, max_colors: null, unique_notes: null },
    toolhead_extras: [],
    connectivity: { wifi: true, ethernet: false, usb: true, camera: true, firmware: "Klipper (форк)", moonraker: false, lan_mode: false },
    materials_supported: ["PLA", "PETG", "ABS", "TPU"],
    dimensions_mm: null,
    price: { msrp_usd: 599, ru_rub: 54900, ru_updated_at: "2026-06-20" },
    unique_features: ["Двойной вентилятор охлаждения", "Керамический нагреватель хотэнда"],
    support_level: "list",
    firmware_ready: null,
    firmware_public: null,
    connector_type: null,
    media: emptyMedia({ hero: demoPhoto(150, 190) }),
    sources: ["https://www.creality.com/products/k1-max-3d-printer", "https://www.creality.com/pages/k1-max-specs"],
    field_sources: {
      "hotend.max_temp_c": { source_url: "https://www.creality.com/pages/k1-max-specs", filled_by: "researcher-creality", ts: "2026-06-01T00:00:00Z", confidence: "high" },
      "price.ru_rub": { source_url: "https://www.creality.com/products/k1-max-3d-printer", filled_by: "researcher-creality", ts: "2026-06-20T00:00:00Z", confidence: "medium" },
    },
    _meta: emptyMeta({ filled_by: "researcher-creality", confidence: "high", gaps: ["dimensions_mm"] }),
  },
  {
    id: "bambulab.x1-carbon",
    slug: "bambulab.x1-carbon",
    brand: "Bambu Lab",
    model: "X1 Carbon",
    aliases: ["X1C"],
    released_at: "2022-11-01",
    status: "shipping",
    kinematics: "corexy",
    type: "fdm",
    enclosed: true,
    build_volume: { x: 256, y: 256, z: 256, shape: "rect", diameter: null },
    hotend: { max_temp_c: 300, max_flow_mm3s: 32, nozzle_default_mm: 0.4, nozzle_swappable: true, material: "hardened steel", hardened: true },
    bed: { max_temp_c: 110, surface: "текстурный PEI", auto_leveling: "inductive" },
    speed: { max_speed_mms: 500, max_accel_mms2: 20000, input_shaping: true },
    multimaterial: { supported: true, system_name: "AMS", max_colors: 16, unique_notes: "до 4 катушек на блок, до 4 блоков подряд" },
    toolhead_extras: [],
    connectivity: { wifi: true, ethernet: true, usb: true, camera: true, firmware: "proprietary", moonraker: false, lan_mode: true },
    materials_supported: ["PLA", "PETG", "ABS", "PA-CF", "PC", "TPU"],
    dimensions_mm: { w: 389, d: 389, h: 458, weight_kg: 14.2 },
    price: { msrp_usd: 1199, ru_rub: 129900, ru_updated_at: "2026-02-01" },
    unique_features: ["LIDAR первого слоя", "AI-детекция сбоя печати"],
    support_level: "list",
    firmware_ready: null,
    firmware_public: null,
    connector_type: null,
    media: emptyMedia({ hero: demoPhoto(20, 40) }),
    sources: ["https://bambulab.com/en/x1"],
    field_sources: {
      "multimaterial.system_name": { source_url: "https://bambulab.com/en/x1", filled_by: "researcher-creality", ts: "2026-02-01T00:00:00Z", confidence: "high" },
    },
    _meta: emptyMeta({ filled_by: "researcher-creality", confidence: "high" }),
  },
  {
    id: "prusa.mk4",
    slug: "prusa.mk4",
    brand: "Prusa",
    model: "MK4",
    aliases: ["Original Prusa MK4"],
    released_at: "2023-06-01",
    status: "shipping",
    kinematics: "cartesian",
    type: "fdm",
    enclosed: false,
    build_volume: { x: 250, y: 210, z: 220, shape: "rect", diameter: null },
    hotend: { max_temp_c: 290, max_flow_mm3s: 25, nozzle_default_mm: 0.4, nozzle_swappable: true, material: null, hardened: null },
    bed: { max_temp_c: 120, surface: null, auto_leveling: "strain-gauge (Loadcell)" },
    speed: null,
    multimaterial: { supported: false, system_name: null, max_colors: null, unique_notes: null },
    toolhead_extras: [],
    connectivity: { wifi: true, ethernet: true, usb: true, camera: false, firmware: "Prusa firmware (Marlin-форк)", moonraker: false, lan_mode: true },
    materials_supported: ["PLA", "PETG", "ABS", "ASA", "PC", "Flex"],
    dimensions_mm: null,
    price: { msrp_usd: 799, ru_rub: null, ru_updated_at: null },
    unique_features: [],
    support_level: "list",
    firmware_ready: null,
    firmware_public: null,
    connector_type: null,
    media: emptyMedia(),
    sources: ["https://www.prusa3d.com/product/original-prusa-mk4-3d-printer-3/"],
    field_sources: {},
    _meta: emptyMeta({ filled_by: "researcher-creality", confidence: "medium", gaps: ["bed.surface", "hotend.material", "price.ru_rub"] }),
  },
  {
    id: "voron.trident",
    slug: "voron.trident",
    brand: "Voron",
    model: "Trident",
    aliases: ["VORON Trident 300"],
    released_at: "2021-09-01",
    status: "shipping",
    kinematics: "corexy",
    type: "fdm",
    enclosed: true,
    build_volume: { x: 300, y: 300, z: 250, shape: "rect", diameter: null },
    hotend: { max_temp_c: null, max_flow_mm3s: null, nozzle_default_mm: 0.4, nozzle_swappable: true, material: null, hardened: null },
    bed: { max_temp_c: 120, surface: "PEI пружинная сталь", auto_leveling: "inductive" },
    speed: { max_speed_mms: 300, max_accel_mms2: 12000, input_shaping: true },
    multimaterial: { supported: false, system_name: null, max_colors: null, unique_notes: null },
    toolhead_extras: [],
    connectivity: { wifi: false, ethernet: false, usb: true, camera: false, firmware: "Klipper", moonraker: true, lan_mode: true },
    materials_supported: ["PLA", "PETG", "ABS", "ASA", "PC", "PA-CF"],
    dimensions_mm: null,
    price: { msrp_usd: null, ru_rub: null, ru_updated_at: null },
    unique_features: ["Открытый DIY-кит — цена зависит от набора комплектующих"],
    support_level: "managed",
    firmware_ready: null,
    firmware_public: null,
    connector_type: "moonraker",
    media: emptyMedia(),
    sources: ["https://vorondesign.com/voron_trident"],
    field_sources: {},
    _meta: emptyMeta({ filled_by: "researcher-creality", confidence: "low", verified: false, gaps: ["hotend.max_temp_c", "hotend.max_flow_mm3s", "price"] }),
  },
  {
    id: "elegoo.saturn4-ultra",
    slug: "elegoo.saturn4-ultra",
    brand: "Elegoo",
    model: "Saturn 4 Ultra",
    aliases: [],
    released_at: "2024-08-01",
    status: "shipping",
    kinematics: null,
    type: "resin-lcd",
    enclosed: true,
    build_volume: { x: 219, y: 123, z: 250, shape: "rect", diameter: null },
    hotend: {},
    bed: { max_temp_c: null, surface: "текстурная плита", auto_leveling: null },
    speed: { max_speed_mms: null, max_accel_mms2: null, input_shaping: null },
    multimaterial: { supported: false, system_name: null, max_colors: null, unique_notes: null },
    toolhead_extras: [],
    connectivity: { wifi: true, ethernet: false, usb: true, camera: false, firmware: "proprietary", moonraker: false, lan_mode: false },
    materials_supported: ["Standard resin", "ABS-like resin"],
    dimensions_mm: null,
    price: { msrp_usd: 429, ru_rub: 42900, ru_updated_at: "2026-05-10" },
    unique_features: ["12K моно-LCD 10 дюймов"],
    support_level: "list",
    firmware_ready: null,
    firmware_public: null,
    connector_type: null,
    media: emptyMedia(),
    sources: ["https://www.elegoo.com/products/saturn-4-ultra"],
    field_sources: {},
    _meta: emptyMeta({ filled_by: "researcher-creality", confidence: "medium", gaps: ["bed.max_temp_c", "speed"] }),
  },
  {
    id: "creality.k2-plus",
    slug: "creality.k2-plus",
    brand: "Creality",
    model: "K2 Plus",
    aliases: [],
    released_at: "2024-11-01",
    status: "shipping",
    kinematics: "corexy",
    type: "fdm",
    enclosed: true,
    build_volume: { x: 350, y: 350, z: 350, shape: "rect", diameter: null },
    hotend: { max_temp_c: 350, max_flow_mm3s: 28, nozzle_default_mm: 0.4, nozzle_swappable: true, material: "hardened steel", hardened: true },
    bed: { max_temp_c: 120, surface: "PEI", auto_leveling: "strain-gauge" },
    speed: { max_speed_mms: 600, max_accel_mms2: 20000, input_shaping: true },
    multimaterial: { supported: true, system_name: "CFS", max_colors: 4, unique_notes: "модульные блоки, до 4 катушек на блок" },
    toolhead_extras: [{ kind: "laser", spec: "10Вт диодный лазер (опциональная голова)" }],
    connectivity: { wifi: true, ethernet: true, usb: true, camera: true, firmware: "Klipper (форк)", moonraker: true, lan_mode: true },
    materials_supported: ["PLA", "PETG", "ABS", "ASA", "TPU", "PA-CF"],
    dimensions_mm: { w: 632, d: 584, h: 682, weight_kg: 26.5 },
    price: { msrp_usd: 1399, ru_rub: 149900, ru_updated_at: "2026-06-28" },
    unique_features: ["Сменная голова (печать/лазер)"],
    support_level: "custom",
    firmware_ready: true,
    firmware_public: false,
    connector_type: "moonraker",
    media: emptyMedia({ hero: demoPhoto(280, 320) }),
    sources: ["https://www.creality.com/products/k2-plus", "https://www.creality.com/pages/k2-plus-specs"],
    field_sources: {
      "toolhead_extras": { source_url: "https://www.creality.com/pages/k2-plus-specs", filled_by: "researcher-creality", ts: "2026-06-28T00:00:00Z", confidence: "high" },
    },
    _meta: emptyMeta({ filled_by: "researcher-creality", confidence: "high" }),
  },
  {
    id: "snapmaker.j1",
    slug: "snapmaker.j1",
    brand: "Snapmaker",
    model: "J1",
    aliases: ["J1s"],
    released_at: "2022-06-01",
    status: "shipping",
    kinematics: "idex",
    type: "fdm",
    enclosed: false,
    build_volume: { x: 324, y: 200, z: 200, shape: "rect", diameter: null },
    hotend: { max_temp_c: 300, max_flow_mm3s: 18, nozzle_default_mm: 0.4, nozzle_swappable: false, material: "hardened steel", hardened: true },
    bed: { max_temp_c: 100, surface: "PEI пружинная сталь", auto_leveling: "inductive" },
    speed: { max_speed_mms: 350, max_accel_mms2: 8000, input_shaping: false },
    multimaterial: { supported: false, system_name: null, max_colors: null, unique_notes: null },
    toolhead_extras: [],
    connectivity: { wifi: true, ethernet: false, usb: true, camera: false, firmware: "proprietary", moonraker: false, lan_mode: false },
    materials_supported: ["PLA", "PETG", "ABS", "TPU"],
    dimensions_mm: null,
    price: { msrp_usd: 1099, ru_rub: 119900, ru_updated_at: "2025-11-01" },
    unique_features: ["Независимые двойные экструдеры (IDEX)", "Дублирование/зеркало печати"],
    support_level: "list",
    firmware_ready: null,
    firmware_public: null,
    connector_type: null,
    media: emptyMedia(),
    sources: ["https://www.snapmaker.com/snapmaker-j1"],
    field_sources: {},
    _meta: emptyMeta({ filled_by: "researcher-creality", confidence: "medium", gaps: ["dimensions_mm"] }),
  },
  {
    id: "creality.ender3-v2",
    slug: "creality.ender3-v2",
    brand: "Creality",
    model: "Ender-3 V2",
    aliases: ["Ender 3 V2"],
    released_at: "2020-09-01",
    status: "eol",
    kinematics: "cartesian",
    type: "fdm",
    enclosed: false,
    build_volume: { x: 220, y: 220, z: 250, shape: "rect", diameter: null },
    hotend: { max_temp_c: 260, max_flow_mm3s: 11, nozzle_default_mm: 0.4, nozzle_swappable: false, material: "brass", hardened: false },
    bed: { max_temp_c: 100, surface: "стекло", auto_leveling: "none" },
    speed: { max_speed_mms: 180, max_accel_mms2: 500, input_shaping: false },
    multimaterial: { supported: false, system_name: null, max_colors: null, unique_notes: null },
    toolhead_extras: [],
    connectivity: { wifi: false, ethernet: false, usb: true, camera: false, firmware: "Marlin", moonraker: false, lan_mode: false },
    materials_supported: ["PLA", "PETG", "TPU"],
    dimensions_mm: null,
    price: { msrp_usd: 279, ru_rub: null, ru_updated_at: null },
    unique_features: [],
    support_level: "list",
    firmware_ready: null,
    firmware_public: null,
    connector_type: null,
    media: emptyMedia(),
    sources: ["https://www.creality.com/products/ender-3-v2-3d-printer"],
    field_sources: {},
    _meta: emptyMeta({ filled_by: "researcher-creality", confidence: "high", gaps: ["price.ru_rub"] }),
  },
  // status=announced — почти пустая карточка (§4.2): только идентичность+дата+источник анонса,
  // ни одной заполненной секции спек. Бренд/модель вымышлены — реального анонса за карточкой нет,
  // это демонстрация состояния «анонс», не факт о реальном продукте.
  {
    id: "vulcan.one",
    slug: "vulcan.one",
    brand: "Vulcan",
    model: "One",
    aliases: [],
    released_at: "2026-09-01",
    status: "announced",
    kinematics: null,
    type: null,
    enclosed: null,
    build_volume: {},
    hotend: {},
    bed: {},
    speed: null,
    multimaterial: { supported: false, system_name: null, max_colors: null, unique_notes: null },
    toolhead_extras: [],
    connectivity: {},
    materials_supported: [],
    dimensions_mm: null,
    price: { msrp_usd: null, ru_rub: null, ru_updated_at: null },
    unique_features: [],
    support_level: "list",
    firmware_ready: null,
    firmware_public: null,
    connector_type: null,
    media: emptyMedia(),
    sources: ["https://example-vendor-announcement.test/vulcan-one"],
    field_sources: {},
    _meta: emptyMeta({
      filled_by: "researcher-creality",
      confidence: "low",
      verified: false,
      gaps: ["build_volume", "hotend", "bed", "price", "connectivity"],
    }),
  },
  // status=rumored — тоже почти пусто, но без официального анонса (только слух-источник).
  {
    id: "nebula.zero",
    slug: "nebula.zero",
    brand: "Nebula",
    model: "Zero",
    aliases: [],
    released_at: null,
    status: "rumored",
    kinematics: null,
    type: "fdm",
    enclosed: null,
    build_volume: {},
    hotend: {},
    bed: {},
    speed: null,
    multimaterial: { supported: false, system_name: null, max_colors: null, unique_notes: null },
    toolhead_extras: [],
    connectivity: {},
    materials_supported: [],
    dimensions_mm: null,
    price: { msrp_usd: null, ru_rub: null, ru_updated_at: null },
    unique_features: [],
    support_level: "list",
    firmware_ready: null,
    firmware_public: null,
    connector_type: null,
    media: emptyMedia(),
    sources: ["https://example-forum-thread.test/nebula-zero-leak"],
    field_sources: {},
    _meta: emptyMeta({ filled_by: "researcher-creality", confidence: "low", verified: false, gaps: ["build_volume", "hotend", "bed", "price"] }),
  },
];

// `GET /printers` живёт под MF-405/MF-839 п.3, ещё не смержен (401 без сессии — блокер §9.4).
// listPrinters имитирует сетевой контракт (Promise) с той же сигнатурой, что примет реальный
// fetch — экран уже пишется против async-функции, подключение реального fetch — правка тела
// этой функции, не вызывающего кода.
export async function listPrintersFixture(): Promise<PrinterRecord[]> {
  return FIXTURES;
}
